name: user_repository
description: Package to manage the user domain
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.5
  freezed: ^2.3.5
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
