name: local_storage_hive
description: Hive implementation of the local storage interface
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  local_storage_interface:
    path: ../local_storage_interface

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
