include: package:very_good_analysis/analysis_options.5.0.0.yaml
linter:
  rules:
    flutter_style_todos: false

analyzer:
  exclude:
    - lib/**.config.dart
    - lib/**.g.dart
    - lib/**.gr.dart
    - lib/**.freezed.dart