name: backend_api_interface
description: Interface and models for the backend API
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  common:
    path: ../common
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  modddels_annotation_dartz: ^0.1.0

dev_dependencies:
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  modddels: ^0.1.5
  test: ^1.19.2
  very_good_analysis: ^5.0.0
